# Generated by Django 5.0.4 on 2024-08-29 21:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0002_alter_propertyphoto_photo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproperty',
            name='description',
            field=models.TextField(default='some description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseproperty',
            name='expected_deposit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseproperty',
            name='property_owner',
            field=models.CharField(default='self', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookvisit',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookvisit',
            name='phone',
            field=models.CharField(default=123456789, max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookvisit',
            name='time',
            field=models.CharField(choices=[('09:00', '09:00 AM'), ('11:00', '11:00 AM'), ('13:00', '01:00 PM'), ('15:00', '03:00 PM'), ('17:00', '05:00 PM'), ('19:00', '07:00 PM')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bookvisit',
            name='visit_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('No Show', 'No Show'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected'), ('Visited', 'Visited'), ('Finalized', 'Finalized'), ('Expired', 'Expired')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='bookvisit',
            unique_together={('user', 'property', 'date', 'time')},
        ),
    ]
