# Generated by Django 5.0.4 on 2024-08-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0004_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproperty',
            name='property_location',
        ),
        migrations.AddField(
            model_name='baseproperty',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseproperty',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookvisit',
            name='visit_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('No Show', 'No Show'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected'), ('Visited', 'Visited'), ('Finalized', 'Finalized'), ('Expired', 'Expired'), ('Rescheduled', 'Rescheduled')], max_length=20),
        ),
    ]
