# Generated by Django 5.0.4 on 2024-09-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0006_baseproperty_rules_propertyphoto_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproperty',
            name='floor_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='residentialproperty',
            name='flat_house',
            field=models.CharField(max_length=100),
        ),
    ]
