# Generated by Django 5.0.4 on 2024-09-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0009_alter_residentialproperty_bhk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialproperty',
            name='bhk',
            field=models.IntegerField(choices=[('1 BHK', 1), ('2 BHK', 2), ('3 BHK', 3), ('4 BHK', 4)], max_length=10),
        ),
    ]
