# Generated by Django 5.0.4 on 2024-09-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0011_alter_residentialproperty_bhk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialproperty',
            name='bhk',
            field=models.IntegerField(choices=[(1, '1 BHK'), (2, '2 BHK'), (3, '3 BHK'), (4, '4 BHK')]),
        ),
    ]
