# Generated by Django 5.0.4 on 2024-09-18 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0012_alter_residentialproperty_bhk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookvisit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_management.baseproperty'),
        ),
    ]
