# Generated by Django 5.0.4 on 2024-05-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantuserprofile",
            name="marital_status",
            field=models.CharField(
                choices=[("unmarried", "Unmarried"), ("married", "Married")],
                default="unmarried",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="landlorduserprofile",
            name="id_proof",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="tenantuserprofile",
            name="id_proof",
            field=models.CharField(blank=True),
        ),
    ]
