# Generated by Django 5.0.4 on 2024-09-03 07:23

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_tenantuserprofile_marital_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlorduserprofile',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='tenantuserprofile',
            name='id_proof',
        ),
        migrations.CreateModel(
            name='IDProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proof', models.CharField(max_length=255)),
                ('id_type', models.CharField(choices=[('passport', 'Passport'), ('driving_license', 'Driving License'), ('aadhar_card', 'Aadhar Card'), ('pan_card', 'Pan Card'), ('Voter ID', 'voter_id')], max_length=255)),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
