# Generated by Django 5.0.4 on 2024-09-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_landlorduserprofile_id_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idproof',
            name='id_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('driving_license', 'Driving License'), ('aadhar_card', 'Aadhar Card'), ('Pan Card', 'pan_card'), ('voter_id', 'Voter ID')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantuserprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantuserprofile',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=255),
        ),
    ]
