# Generated by Django 5.0.4 on 2024-09-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_idproof_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idproof',
            name='id_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('driving_license', 'Driving License'), ('aadhar_card', 'Aadhar Card'), ('Pan Card', 'pan_card'), ('voter_id', 'Voter ID')], max_length=255),
        ),
    ]
